apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sample-microservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-sample-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sample-microservice
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sample-microservice
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.env.APP_VERSION }}"
            - name: CLUSTER
              value: "{{ .Values.env.CLUSTER }}"
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
