apiVersion: v1
kind: Service
metadata:
  name: sample-microservice
  namespace: platform
spec:
  selector:
    app: sample-microservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
